# Generated by Django 3.2.13 on 2022-10-05 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
    ]
