# Generated by Django 3.1.7 on 2022-10-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eithers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='issue_a',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='issue_b',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
