# Generated by Django 3.1.7 on 2022-10-06 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eithers', '0004_auto_20221006_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='question_id',
        ),
    ]
